### ISSUE TITLE
Global Sync Functionality Not Working

### ISSUE THREAD

**Issue by smaylath** [pbs/pbs-media-manager-craft-plugin-food#6]
Reference: https://github.com/pbs/food-site/issues/169

1. i'd like to re-sync a show on the PBS Food site, re-grabbing the imagery.
2. Navigating to the [sync](https://food-prod.console.pbs.org/admin/mediamanager/synchronize) page, I scroll to the bottom and select "synchronize show entries".
3. After selecting what i'd like to sync, I hit the red "update all media" button
4. The system attempts to start an 'all shows' sync, but you can see nearly every program fails in the queue manager.

**Comment by smaylath** [comment]
@crzbarcea would you be able to add Sam to this repo? I'd like to be able to tag him in here to share info as we work on this :) Thanks!

**Comment by andrewmenich** [comment]
The issues described above have been resolved in #7 #8 #9 and are on the develop environment for review. Pinging Sam offline for now until he's added to the repo.

**Comment by SamLaneyPBS** [comment]
Confirmed this looks good. Thank you, Andrew

**Comment by smaylath** [comment]
Thank you! Andrew has opened a PR to merge in these changes and requested @crzbarcea 's approval
We'd recommend any deployments to production happen after the weekend.

**Comment by smaylath** [comment]
Confirming this was deployed to production
